/* This SAS program was automatically generated by Stat/Transfer ver.12.1.334.0516 */

/* ENCODING CP1252 */

/* The following line should contain the complete path and name of your raw data file */
FILENAME datafile 'M:/data/ist3/ist3.dat' ;

/* The following line should contain the directory in which you wish your SAS file to be stored */
libname library 'M:/data/ist3/' ;

/* The following line contains the name (without the extension) for your SAS dataset */
%LET dataset = ist3 ;

DATA library.&dataset ;
INFILE datafile LRECL=512;
INPUT
   randhosp_id $ 1-3        randpat_id $ 4-8         pretrialexp  9        
   country $ 10-18          trialphase $ 19-25       phase  26             
   itt_treat  27            age  28-33               gender  34            
   deathcode $ 35-36        deathdate_unknown  37    randyear  38-41       
   randmonth  42-43         randhour  44-45          randmin  46-47        
   randdelay  48-64         livealone_rand  65-66    indepinadl_rand  67   
   nobleed_rand  68         infarct  69              antiplat_rand  70     
   atrialfib_rand  71       sbprand  72-74           dbprand  75-77        
   weight  78-80            glucose  81-82           gcs_eye_rand  83      
   gcs_motor_rand  84       gcs_verbal_rand  85      gcs_score_rand  86-87 
   nihss  88-89             liftarms_rand  90        ablewalk_rand  91     
   weakface_rand  92        weakarm_rand  93         weakleg_rand  94      
   dysphasia_rand  95       hemianopia_rand  96      visuospat_rand  97    
   brainstemsigns_rand  98   otherdeficit_rand  99    stroketype  100       
   pred_nihss  101          konprob  102-120         randvioltype $ 121-156
   other_antiplat_pre  157   anticoag_pre  158-159    recinfus  160         
   gotbolus $ 161           infus_start $ 162        infus_halt $ 163      
   totdose  164-168         sbpstart  169-171        sbp30min  172-174     
   sbp60min  175-177        sbp24h  178-180          dbpstart  181-183     
   dbp30min  184-186        dbp60min  187-189        dbp24h  190-192       
   treatdelay  193-208      recR  209                asl $ 210             
   R_scantype  211          R_scannorm $ 212         recP  213             
   P_scantype  214          P_scannorm $ 215         rec7  216             
   consent_type  217        aspirin_pre  218-219     dipyridamole_pre  220-221
   clopidogrel_pre  222-223   lowdose_heparin_pre  224-225
   fulldose_heparin_pre  226-227   warfarin_pre  228-229 
   antithromb_pre  230      hypertension_pre  231-232   diabetes_pre  233-234 
   stroke_pre  235-236      aspirin_day1  237-238    antiplatelet_day1  239-240
   lowdose_heparin_day1  241-242   full_anticoag_day1  243-244
   lowerBP_day1  245-246    nontrial_thromb_day1  247-248
   iv_fluids_day1  249-250   insulin_day1  251-252    aspirin_days2to7  253-254
   antiplatelet_days2to7  255-256   lowdose_heparin_days2to7  257-258
   full_anticoag_days2to7  259-260   lowerBP_days2to7  261-262
   nontrial_thromb_days2to7  263-264   nasogastric_days2to7  265-266
   antibiotics_days2to7  267-268   findiag7  269         
   brainsite7  270          haem_type7  271          nonstroke_type7  272  
   med_adno  273            critcareno  274          strk_unitno  275      
   genwardno  276           adjudicated  277         sevendaycase  278-279 
   final_status $ 280-281   sich7  282               dead7  283            
   myocard_infarct  284     extracranial_bleed  285   allergic_reaction  286
   other_effect  287        adverse_reaction  288    gcs_eye_7  289-290    
   gcs_motor_7  291-292     gcs_verbal_7  293-294    liftarms_7  295-296   
   ablewalk_7  297-298      indepinadl_7  299-300    destination  301      
   recsix  302              sixmonthform  303        sixcompleted_by  304  
   ohs6  305                ordinal6  306            aliveind6  307        
   alivefav6  308           dead6mo  309             imputed6  310         
   aspirin6  311-312        bloodthin6  313-314      clotbust6  315-316    
   stocking6  317-318       gotprobs6  319-320       needhelp6  321-322    
   walkhelp6  323-324       speakprob6  325-326      mobility6  327-328    
   selfcare6  329-330       activities6  331-332     pain6  333-334        
   anxiety6  335-336        wherelive6  337-338      howlive6  339-340     
   euroqol6  341-343        receighteen  344         eighteenmonthform  345
   eighteencompleted_by  346   aspirin18  347-348       bloodthin18  349-350  
   clotbust18  351-352      stocking18  353-354      gotprobs18  355-356   
   needhelp18  357-358      walkhelp18  359-360      speakprob18  361-362  
   mobility18  363-364      selfcare18  365-366      activities18  367-368 
   pain18  369-370          anxiety18  371-372       wherelive18  373-374  
   howlive18  375-376       euroqol18  377-380       deadordep18  381      
   ohs18  382               ordinal18  383           aliveind18  384       
   alivefav18  385          yrfu_code $ 386-387      waiver_code $ 388-389 
   extracranial_bleed_site $ 390-391   other_effect_code $ 392-394
   nostartcode $ 395-397    deadordep6  398          missing6  399         
   missing18  400           event_days  401          agecat $ 402-406      
   ageimp  407-412          age_true  413-414        R_acuteic $ 415       
   hypodeg $ 416            hypodegsite $ 417        mca $ 418             
   affmca $ 419             aspcau $ 420             asplen $ 421          
   aspins $ 422             aspint $ 423             aspm1 $ 424           
   aspm2 $ 425              aspm3 $ 426              aspm4 $ 427           
   aspm5 $ 428              aspm6 $ 429              oial $ 430            
   aca $ 431                pca $ 432                subinf $ 433          
   cbzinf $ 434             cinf $ 435               stem $ 436            
   tisswell $ 437           hdart1 $ 438             hdart2 $ 439          
   hdart3 $ 440             hdart4 $ 441             hdart5 $ 442          
   hdart6 $ 443             hdart7 $ 444             seclesion $ 445       
   redbtvola $ 446          redbtvolb $ 447          wmla $ 448            
   wmlp $ 449               oldlesion $ 450          oldlesion1 $ 451      
   oldlesion2 $ 452         oldlesion3 $ 453         oldlesion4 $ 454      
   oldlesion5 $ 455         oldlesion6 $ 456         nslesion $ 457        
   nslesion1 $ 458          nslesion2 $ 459          nslesion3 $ 460       
   nslesion4 $ 461          nslesion5 $ 462          scanqual $ 463        
   R_infarct_size  464      apca  465                subinf1  466          
   cbzinf1  467             cinf1  468               stem1  469            
   aca1  470                pca1  471                R_infarct_territory  472
   R_hypodensity  473       R_swelling  474          R_hyperdense_arteries  475
   R_atrophy  476           R_whitematter  477       R_oldlesion  478      
   R_nonstroke_lesion  479   R_isch_change  480       R_mca_aspects  481-482
   R_tot_aspects  483-484   R_hyperdensity  485      vis_infarct  486      
   time_to_PH  487          PH_haemorrhage  488      surv6  489-491        
   censor6  492             censor18  493            surv18  494-496       
   plan18  497              UKextra  498             disab_unknown6  499   
   vital_and_disabunknown6  500   disab_unknown18  501  
   vital_and_disabunknown18  502   treatment $ 503-509   
   haltcode $ 510-512     ;                       

LABEL
   randhosp_id = "Hosp_ID (anonymised)"
   randpat_id = "Patient_ID (anonymised)"
   pretrialexp = "Centre with pre-trial experience of thrombolysis"
   country = "Country"
   trialphase = "Trial phase"
   itt_treat = "Allocated treatment"
   age = "Age at randomisation"
   gender = "Gender"
   deathcode = "Cause of death (IST3 E codes)"
   randyear = "Year of randomisation"
   randmonth = "Month of randomisation"
   randhour = "Local hour of randomisation"
   randmin = "Local minute of randomisation"
   randdelay = "Delay (hours) from stroke to randomisation"
   livealone_rand = "Lived alone before stroke?"
   indepinadl_rand = "Independent in ADL before stroke?"
   nobleed_rand = "Imaging excluded intracranial haemorrhage?"
   infarct = "Recent ischaemic change likely cause of this stroke?"
   antiplat_rand = "Received antiplatelet drugs in last 48 hours?"
   atrialfib_rand = "Patient in atrial fibrillation at randomisation?"
   sbprand = "Systolic BP at randomisation (mm Hg)"
   dbprand = "Diastolic BP at randomisation (mm Hg)"
   weight = "Estimated weight (kg)"
   glucose = "Blood glucose (mmol/L)"
   gcs_eye_rand = "Best eye response (Glasgow Coma Scale) at randomisation"
   gcs_motor_rand = "Best motor response (Glasgow Coma Scale) at randomisation"
   gcs_verbal_rand = "Best verbal response (Glasgow Coma Scale) at randomisation"
   gcs_score_rand = "Total Glasgow Coma Scale score at randomisation"
   nihss = "Total NIH Stroke Score at randomisation"
   liftarms_rand = "Able to lift both arms off bed at randomisation"
   ablewalk_rand = "Able to walk without help at randomisation"
   weakface_rand = "Unilateral weakness affecting face at randomisation"
   weakarm_rand = "Unilateral weakness affecting arm or hand at randomisation"
   weakleg_rand = "Unilateral weakness affecting leg or foot at randomisation"
   dysphasia_rand = "Dysphasia at randomisation"
   hemianopia_rand = "Homonymous hemianopia at randomisation"
   visuospat_rand = "Visuospatial disorder at randomisation"
   brainstemsigns_rand = "Brainstem or cerebellar signs at randomisation"
   otherdeficit_rand = "Other neurological deficit at randomisation"
   stroketype = "Stroke subtype"
   pred_nihss = "NIHSS predicted?"
   konprob = "Probability of good outcome based on Konig model"
   randvioltype = "Protocol deviation at randomisation"
   other_antiplat_pre = "Pre-trial treatment with anti-platelets other than aspirin"
   anticoag_pre = "Pre-trial treatment with anti-coagulants"
   recinfus = "Infusion form received"
   gotbolus = "rtPA bolus given (Y/N)"
   infus_start = "Post-bolus infusion started (Y/N)"
   infus_halt = "Infusion halted (Y/N)"
   totdose = "Total mg alteplase dose (bolus + infusion)"
   sbpstart = "SBP at start of treatment"
   sbp30min = "SBP after 30 mins"
   sbp60min = "SBP after 60 mins"
   sbp24h = "SBP after 24 hours"
   dbpstart = "DBP at start of treatment"
   dbp30min = "DBP after 30 mins"
   dbp60min = "DBP after 60 mins"
   dbp24h = "DBP after 24 hours"
   treatdelay = "Time (hr) from stroke to treatment"
   recR = "R scan received"
   asl = "Adjudicated side of lesion"
   R_scantype = "Type (CT/MR) of R scan"
   R_scannorm = "R scan normal?"
   recP = "P scan received"
   P_scantype = "Type of P scan"
   P_scannorm = "P Scan completely normal"
   rec7 = "Seven day form received"
   consent_type = "Type of patient consent"
   aspirin_pre = "Aspirin before admission?"
   dipyridamole_pre = "Dipyridamole before admission?"
   clopidogrel_pre = "Clopidogrel before admission?"
   lowdose_heparin_pre = "Low dose heparin before admission?"
   fulldose_heparin_pre = "Full dose heparin before admission?"
   warfarin_pre = "Warfarin before admission?"
   antithromb_pre = "Other antithrombotic agents before admission?"
   hypertension_pre = "Treatment for hypertension before admission?"
   diabetes_pre = "Treatment for diabetes before admission?"
   stroke_pre = "History of previous stroke or TIA?"
   aspirin_day1 = "Aspirin in first 24 hours?"
   antiplatelet_day1 = "Other antiplatelets in first 24 hours?"
   lowdose_heparin_day1 = "Low dose heparin or low molecular weight heparin in first 24 hours?"
   full_anticoag_day1 = "Full anti-coagulation in first 24 hours?"
   lowerBP_day1 = "Treatment to lower blood pressure in first 24 hours?"
   nontrial_thromb_day1 = "Non-trial thrombolysis in first 24 hours?"
   iv_fluids_day1 = "Intravenous fluids in first 24 hours?"
   insulin_day1 = "Insulin in first 24 hours?"
   aspirin_days2to7 = "Aspirin between 24 hours & 7 days?"
   antiplatelet_days2to7 = "Other antiplatelets between 24 hours & 7 days?"
   lowdose_heparin_days2to7 = "Low dose heparin or low molecular weight heparin between 24 hours & 7 days?"
   full_anticoag_days2to7 = "Full anti-coagulation between 24 hours & 7 days?"
   lowerBP_days2to7 = "Treatment to lower blood pressure between 24 hours & 7 days?"
   nontrial_thromb_days2to7 = "Non-trial thrombolysis between 24 hours & 7 days?"
   nasogastric_days2to7 = "Nasogastric tube or percutaneous gastrostomy between 24 hours & 7 days?"
   antibiotics_days2to7 = "Antibiotics between 24 hours & 7 days?"
   findiag7 = "Final diagnosis of initial randomising event (7 day form)"
   brainsite7 = "Location of initial ischaemic stroke (7 day form)"
   haem_type7 = "Type of initial haemorrhagic stroke (7 day form)"
   nonstroke_type7 = "Type of non-stroke cause (7 day form)"
   med_adno = "Number of nights in Medical Admissions Unit in first 7 days"
   critcareno = "Number of nights in Critical Care Unit in first 7 days"
   strk_unitno = "Number of nights in Stroke Unit in first 7 days"
   genwardno = "Number of nights in General Ward in first 7 days"
   adjudicated = "Patient had adjudicated event in first 7 days"
   sevendaycase = "Type of adjudicated event in first 7 days"
   final_status = "Adjudicated final status"
   sich7 = "Symptomatic ICH within 7 days"
   dead7 = "Died <=7 days after randomisation"
   myocard_infarct = "Myocardial infarction in first 7 days"
   extracranial_bleed = "Major extracranial bleed in first 7 days"
   allergic_reaction = "Major allergic reaction in first 7 days"
   other_effect = "Other side effect in first 7 days"
   adverse_reaction = "Other adverse reaction in first 7 days"
   gcs_eye_7 = "Best eye response at 7 days (Glasgow Coma Scale)"
   gcs_motor_7 = "Best motor response at 7 days (Glasgow Coma Scale)"
   gcs_verbal_7 = "Best verbal response at 7 days (Glasgow Coma Scale)"
   liftarms_7 = "Able to lift both arms off bed at 7 days"
   ablewalk_7 = "Able to walk without help at 7 days"
   indepinadl_7 = "Independent in activities of daily living at 7 days"
   destination = "Destination to which patient discharged from hospital"
   recsix = "Six month form received"
   sixmonthform = "Type of six month form"
   sixcompleted_by = "Person completing 6 month form"
   ohs6 = "OHS from 6 month form"
   ordinal6 = "OHS from 6 month form, with levels 4,5,6 combined"
   aliveind6 = "Alive and independent at 6 months (OHS<=2)"
   alivefav6 = "Alive and favourable outcome at 6 months (OHS<=1)"
   dead6mo = "Died before 6 months"
   imputed6 = "OHS at 6 months imputed"
   aspirin6 = "Aspirin given on admission day (6 month form)"
   bloodthin6 = "Blood thinning injections given on admission day (6 month form)"
   clotbust6 = "Clot busting drugs given on admission day (6 month form)"
   stocking6 = "Special stockings given on admission day (6 month form)"
   gotprobs6 = "Stroke left patient with problems (6 month form)"
   needhelp6 = "Needs help with everyday activities (6 month form)"
   walkhelp6 = "Needs help to walk (6 month form)"
   speakprob6 = "Major problems speaking (6 month form)"
   mobility6 = "Mobility problems (6 month form)"
   selfcare6 = "Washing or dressing problems (6 month form)"
   activities6 = "Usual activities problems (6 month form)"
   pain6 = "Pain or discomfort (6 month form)"
   anxiety6 = "Anxiety or depression (6 month form)"
   wherelive6 = "Where patient lives now (6 month form, patient not in hospital)"
   howlive6 = "How patient lives now (6 month form, patient not in hospital)"
   euroqol6 = "Health state (Euroqol) at 6 months"
   receighteen = "18 month form received"
   eighteenmonthform = "Type of eighteen month form"
   eighteencompleted_by = "Person completing 18 month form"
   aspirin18 = "Aspirin given on admission day (18 month form)"
   bloodthin18 = "Blood thinning injections given on admission day (18 month form)"
   clotbust18 = "Clot busting drugs given on admission day (18 month form)"
   stocking18 = "Special stockings given on admission day (18 month form)"
   gotprobs18 = "Stroke left patient with problems (18 month form)"
   needhelp18 = "Needs help with everyday activities (18 month form)"
   walkhelp18 = "Needs help to walk (18 month form)"
   speakprob18 = "Major problems speaking (18 month form)"
   mobility18 = "Mobility problems (18 month form)"
   selfcare18 = "Washing or dressing problems (18 month form)"
   activities18 = "Usual activities problems (18 month form)"
   pain18 = "Pain or discomfort (18 month form)"
   anxiety18 = "Anxiety or depression (18 month form)"
   wherelive18 = "Where patient lives now (18 month form, patient not in hospital)"
   howlive18 = "How patient lives now (18 month form, patient not in hospital)"
   euroqol18 = "Health state (Euroqol) at 18 months"
   deadordep18 = "Dead or dependent at 18 months (OHS>=3)"
   ohs18 = "OHS from 18 month form"
   ordinal18 = "OHS from 18 month form, with levels 4,5,6 combined"
   aliveind18 = "Alive and independent at 18 months (OHS<=2)"
   alivefav18 = "Alive and favourable outcome at 18 months (OHS<=1)"
   yrfu_code = "Reasons for lack of 18 month follow-up (L codes)"
   waiver_code = "Reason for waiver of consent (A codes)"
   extracranial_bleed_site = "Site of extracranial bleed (C codes)"
   other_effect_code = "D code for other side effects recorded on 7 day form"
   nostartcode = "Reason treatment not started (J codes)"
   deadordep6 = "Dead or dependent at 6 months (OHS>=3)"
   missing6 = "OHS at 6 months missing"
   missing18 = "Alive at 18 mo and form not returned"
   R_acuteic = "R scan shows acute ischaemic change?"
   hypodeg = "Degree of acute hypodensity"
   hypodegsite = "Site of maximum visible swelling"
   mca = "Changes in middle cerebral aretery"
   affmca = "Site/size of lesion of MCA territory"
   aspcau = "Caudate region shows ischaemic change"
   asplen = "Lentiform region shows ischaemic change"
   aspins = "Insula region shows ischaemic change"
   aspint = "Internal capsule region shows ischaemic change"
   aspm1 = "M1 region shows ischaemic change"
   aspm2 = "M2 region shows ischaemic change"
   aspm3 = "M3 region shows ischaemic change"
   aspm4 = "M4 region shows ischaemic change"
   aspm5 = "M5 region shows ischaemic change"
   aspm6 = "M6 region shows ischaemic change"
   oial = "Other part of brain involved in acute ischaemic lesion?"
   aca = "Anterior cerebral artery affected? (4 levels)"
   pca = "Posterior cerebral artery affected?(4 levels)"
   subinf = "Acute small subcortical infarcts?(5 areas)"
   cbzinf = "Acute cortical borderzone infarcts?(4 levels)"
   cinf = "Acute cerebellar infarct?(4 levels)"
   stem = "Acute brainstem infarct?(4 levels)"
   tisswell = "Degree of tissue swelling in acute infarct"
   hdart1 = "Hyperdense artery sign in MCA main stem"
   hdart2 = "Hyperdense artery sign in Insular MCA"
   hdart3 = "Hyperdense artery sign in Internal Carotid Artery"
   hdart4 = "Hyperdense artery sign in Anterior Cerebral Artery"
   hdart5 = "Hyperdense artery sign in Posterior Cerebral Artery"
   hdart6 = "Hyperdense artery sign in Basilar Artery"
   hdart7 = "Hyperdense artery sign in Vertebral Artery"
   seclesion = "Another minor new ischaemic lesion?"
   redbtvola = "Central atrophy"
   redbtvolb = "Cortical atrophy"
   wmla = "Anterior white matter lucencies"
   wmlp = "Posterior white matter lucencies"
   oldlesion = "Any old vascular lesions?"
   oldlesion1 = "Old cortical infarcts"
   oldlesion2 = "Old striatocapsular infarcts"
   oldlesion3 = "Old borderzone infarcts"
   oldlesion4 = "Old lacunar infarcts"
   oldlesion5 = "Old brainstem/cerebellar infarcts"
   oldlesion6 = "Probable old haemorrhage"
   nslesion = "Any non-stroke lesion?"
   nslesion1 = "Cerebral tumour"
   nslesion2 = "Encephalitis"
   nslesion3 = "Demyelation"
   nslesion4 = "Cerebral abcess"
   nslesion5 = "Other, eg contusion"
   scanqual = "Scan quality"
   R_infarct_size = "Infarct size (from R scan)"
   apca = "Infarcts in ACA / PCA territory"
   subinf1 = "Acute small subcortical infarcts?(0/1)"
   cbzinf1 = "Acute cortical borderzone infarcts?(0/1)"
   cinf1 = "Acute cerebellar infarct?(0/1)"
   stem1 = "Acute brainstem infarct?(0/1)"
   aca1 = "Anterior cerebral artery affected? (0/1)"
   pca1 = "Posterior cerebral artery affected?(0/1)"
   R_infarct_territory = "Infarct territory (from R scan)"
   R_hypodensity = "Degree of acute hypodensity (R scan)"
   R_swelling = "Degree of tissue swelling in acute infarct (R scan)"
   R_hyperdense_arteries = "Hyperdense arteries visible on R scan"
   R_atrophy = "Atrophy visible on R scan"
   R_whitematter = "White matter visible on R scan"
   R_oldlesion = "Old vascular lesion visible on R scan"
   R_nonstroke_lesion = "Non-stroke lesion visible on R scan"
   R_isch_change = "Ischaemic change visible on R scan"
   R_mca_aspects = "Aspects score (max 10) for Middle cerebral artery (R scan)"
   R_tot_aspects = "Total aspects score (max 12) including ACA/PCA (R scan)"
   haltcode = "Reason infusion interrupted (I codes)" ;

LENGTH
   pretrialexp 3            phase 3                  itt_treat 3           
   gender 3                 deathdate_unknown 3      randyear 4            
   randmonth 3              randhour 3               randmin 3             
   livealone_rand 3         indepinadl_rand 3        nobleed_rand 3        
   infarct 3                antiplat_rand 3          atrialfib_rand 3      
   sbprand 4                dbprand 4                weight 4              
   glucose 3                gcs_eye_rand 3           gcs_motor_rand 3      
   gcs_verbal_rand 3        gcs_score_rand 3         nihss 3               
   liftarms_rand 3          ablewalk_rand 3          weakface_rand 3       
   weakarm_rand 3           weakleg_rand 3           dysphasia_rand 3      
   hemianopia_rand 3        visuospat_rand 3         brainstemsigns_rand 3 
   otherdeficit_rand 3      stroketype 3             pred_nihss 3          
   other_antiplat_pre 3     anticoag_pre 3           recinfus 3            
   sbpstart 4               sbp30min 4               sbp60min 4            
   sbp24h 4                 dbpstart 4               dbp30min 4            
   dbp60min 4               dbp24h 4                 recR 3                
   R_scantype 3             recP 3                   P_scantype 3          
   rec7 3                   consent_type 3           aspirin_pre 3         
   dipyridamole_pre 3       clopidogrel_pre 3        lowdose_heparin_pre 3 
   fulldose_heparin_pre 3   warfarin_pre 3           antithromb_pre 3      
   hypertension_pre 3       diabetes_pre 3           stroke_pre 3          
   aspirin_day1 3           antiplatelet_day1 3      lowdose_heparin_day1 3
   full_anticoag_day1 3     lowerBP_day1 3           nontrial_thromb_day1 3
   iv_fluids_day1 3         insulin_day1 3           aspirin_days2to7 3    
   antiplatelet_days2to7 3   lowdose_heparin_days2to7 3   full_anticoag_days2to7 3
   lowerBP_days2to7 3       nontrial_thromb_days2to7 3   nasogastric_days2to7 3
   antibiotics_days2to7 3   findiag7 3               brainsite7 3          
   haem_type7 3             nonstroke_type7 3        med_adno 3            
   critcareno 3             strk_unitno 3            genwardno 3           
   adjudicated 3            sevendaycase 3           sich7 3               
   dead7 3                  myocard_infarct 3        extracranial_bleed 3  
   allergic_reaction 3      other_effect 3           adverse_reaction 3    
   gcs_eye_7 3              gcs_motor_7 3            gcs_verbal_7 3        
   liftarms_7 3             ablewalk_7 3             indepinadl_7 3        
   destination 3            recsix 3                 sixmonthform 3        
   sixcompleted_by 3        ohs6 3                   ordinal6 3            
   aliveind6 3              alivefav6 3              dead6mo 3             
   imputed6 3               aspirin6 3               bloodthin6 3          
   clotbust6 3              stocking6 3              gotprobs6 3           
   needhelp6 3              walkhelp6 3              speakprob6 3          
   mobility6 3              selfcare6 3              activities6 3         
   pain6 3                  anxiety6 3               wherelive6 3          
   howlive6 3               euroqol6 3               receighteen 3         
   eighteenmonthform 3      eighteencompleted_by 3   aspirin18 3           
   bloodthin18 3            clotbust18 3             stocking18 3          
   gotprobs18 3             needhelp18 3             walkhelp18 3          
   speakprob18 3            mobility18 3             selfcare18 3          
   activities18 3           pain18 3                 anxiety18 3           
   wherelive18 3            howlive18 3              deadordep18 3         
   ohs18 3                  ordinal18 3              aliveind18 3          
   alivefav18 3             deadordep6 3             missing6 3            
   missing18 3              event_days 3             age_true 3            
   R_infarct_size 3         apca 3                   subinf1 3             
   cbzinf1 3                cinf1 3                  stem1 3               
   aca1 3                   pca1 3                   R_infarct_territory 3 
   R_hypodensity 3          R_swelling 3             R_hyperdense_arteries 3
   R_atrophy 3              R_whitematter 3          R_oldlesion 3         
   R_nonstroke_lesion 3     R_isch_change 3          R_mca_aspects 3       
   R_tot_aspects 3          R_hyperdensity 3         vis_infarct 3         
   time_to_PH 3             PH_haemorrhage 3         surv6 4               
   censor6 3                censor18 3               surv18 4              
   plan18 3                 UKextra 3                disab_unknown6 3      
   vital_and_disabunknown6 3   disab_unknown18 3        vital_and_disabunknown18 3 ;



RUN ;
